//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.22 at 07:53:14 PM MSK 
//


package localhost._8080.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CountryDto.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CountryDto">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RUSSIA"/>
 *     &lt;enumeration value="SPAIN"/>
 *     &lt;enumeration value="NORTH_KOREA"/>
 *     &lt;enumeration value="JAPAN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CountryDto")
@XmlEnum
public enum CountryDto {

    RUSSIA,
    SPAIN,
    NORTH_KOREA,
    JAPAN;

    public String value() {
        return name();
    }

    public static CountryDto fromValue(String v) {
        return valueOf(v);
    }

}
