//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.22 at 04:03:24 PM MSK 
//


package localhost._8080.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subString"
})
@XmlRootElement(name = "getArrayProductsWhereNameIncludeSubstringRequest")
public class GetArrayProductsWhereNameIncludeSubstringRequest {

    @XmlElement(required = true)
    protected String subString;

    /**
     * Gets the value of the subString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubString() {
        return subString;
    }

    /**
     * Sets the value of the subString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubString(String value) {
        this.subString = value;
    }

}
