//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.22 at 04:03:24 PM MSK 
//


package localhost._8080.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8080.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8080.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProductsByFilterRequest }
     * 
     */
    public GetProductsByFilterRequest createGetProductsByFilterRequest() {
        return new GetProductsByFilterRequest();
    }

    /**
     * Create an instance of {@link UpdateProductByIdResponse }
     * 
     */
    public UpdateProductByIdResponse createUpdateProductByIdResponse() {
        return new UpdateProductByIdResponse();
    }

    /**
     * Create an instance of {@link ProductDto }
     * 
     */
    public ProductDto createProductDto() {
        return new ProductDto();
    }

    /**
     * Create an instance of {@link Ping }
     * 
     */
    public Ping createPing() {
        return new Ping();
    }

    /**
     * Create an instance of {@link GetArrayProductsWhereNameUnique }
     * 
     */
    public GetArrayProductsWhereNameUnique createGetArrayProductsWhereNameUnique() {
        return new GetArrayProductsWhereNameUnique();
    }

    /**
     * Create an instance of {@link CountProductsWherePriceHigherResponse }
     * 
     */
    public CountProductsWherePriceHigherResponse createCountProductsWherePriceHigherResponse() {
        return new CountProductsWherePriceHigherResponse();
    }

    /**
     * Create an instance of {@link GetProductByIdResponse }
     * 
     */
    public GetProductByIdResponse createGetProductByIdResponse() {
        return new GetProductByIdResponse();
    }

    /**
     * Create an instance of {@link GetArrayProductsWhereNameIncludeSubstringRequest }
     * 
     */
    public GetArrayProductsWhereNameIncludeSubstringRequest createGetArrayProductsWhereNameIncludeSubstringRequest() {
        return new GetArrayProductsWhereNameIncludeSubstringRequest();
    }

    /**
     * Create an instance of {@link GetAllProducts }
     * 
     */
    public GetAllProducts createGetAllProducts() {
        return new GetAllProducts();
    }

    /**
     * Create an instance of {@link GetProductsByFilterResponse }
     * 
     */
    public GetProductsByFilterResponse createGetProductsByFilterResponse() {
        return new GetProductsByFilterResponse();
    }

    /**
     * Create an instance of {@link CreateProductResponse }
     * 
     */
    public CreateProductResponse createCreateProductResponse() {
        return new CreateProductResponse();
    }

    /**
     * Create an instance of {@link GetArrayProductsWhereNameIncludeSubstringResponse }
     * 
     */
    public GetArrayProductsWhereNameIncludeSubstringResponse createGetArrayProductsWhereNameIncludeSubstringResponse() {
        return new GetArrayProductsWhereNameIncludeSubstringResponse();
    }

    /**
     * Create an instance of {@link ExceptionDtoResponse }
     * 
     */
    public ExceptionDtoResponse createExceptionDtoResponse() {
        return new ExceptionDtoResponse();
    }

    /**
     * Create an instance of {@link GetProductByIdRequest }
     * 
     */
    public GetProductByIdRequest createGetProductByIdRequest() {
        return new GetProductByIdRequest();
    }

    /**
     * Create an instance of {@link UpdateProductByIdRequest }
     * 
     */
    public UpdateProductByIdRequest createUpdateProductByIdRequest() {
        return new UpdateProductByIdRequest();
    }

    /**
     * Create an instance of {@link CoordinatesDto }
     * 
     */
    public CoordinatesDto createCoordinatesDto() {
        return new CoordinatesDto();
    }

    /**
     * Create an instance of {@link PersonDto }
     * 
     */
    public PersonDto createPersonDto() {
        return new PersonDto();
    }

    /**
     * Create an instance of {@link CreateProductRequest }
     * 
     */
    public CreateProductRequest createCreateProductRequest() {
        return new CreateProductRequest();
    }

    /**
     * Create an instance of {@link DeleteProductByIdRequest }
     * 
     */
    public DeleteProductByIdRequest createDeleteProductByIdRequest() {
        return new DeleteProductByIdRequest();
    }

    /**
     * Create an instance of {@link CountProductsWherePriceHigherRequest }
     * 
     */
    public CountProductsWherePriceHigherRequest createCountProductsWherePriceHigherRequest() {
        return new CountProductsWherePriceHigherRequest();
    }

    /**
     * Create an instance of {@link GetProductsByFilterRequest.OrderBy }
     * 
     */
    public GetProductsByFilterRequest.OrderBy createGetProductsByFilterRequestOrderBy() {
        return new GetProductsByFilterRequest.OrderBy();
    }

    /**
     * Create an instance of {@link LocationDto }
     * 
     */
    public LocationDto createLocationDto() {
        return new LocationDto();
    }

}
