//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.22 at 04:03:24 PM MSK 
//


package localhost._8080.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitOfMeasureDto.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnitOfMeasureDto">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="KILOGRAMS"/>
 *     &lt;enumeration value="METERS"/>
 *     &lt;enumeration value="CENTIMETERS"/>
 *     &lt;enumeration value="SQUARE_METERS"/>
 *     &lt;enumeration value="MILLILITERS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UnitOfMeasureDto")
@XmlEnum
public enum UnitOfMeasureDto {

    KILOGRAMS,
    METERS,
    CENTIMETERS,
    SQUARE_METERS,
    MILLILITERS;

    public String value() {
        return name();
    }

    public static UnitOfMeasureDto fromValue(String v) {
        return valueOf(v);
    }

}
