server:
  port: ${APPLICATION_PORT:8082}

spring:
  application:
    name: ${APPLICATION_NAME:gateway}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

service:
  first-service:
    url: http://${BASIC_HOST:localhost}:${BASIC_PORT:8080}/ws
